## LU decompostion

In [1]:
from numpy import array
from scipy.linalg import lu

In [3]:
A = array([[3,0],[4,5]])
print(A)

[[3 0]
 [4 5]]


In [4]:
P, L, U = lu(A)

In [7]:
print(P)

[[ 0.  1.]
 [ 1.  0.]]


In [5]:
print(L)

[[ 1.    0.  ]
 [ 0.75  1.  ]]


In [6]:
print(U)

[[ 4.    5.  ]
 [ 0.   -3.75]]


In [11]:
B=P.dot(L).dot(U)
print(B)

[[ 3.  0.]
 [ 4.  5.]]


In [13]:
C=L.dot(U)
print(C)

[[ 4.  5.]
 [ 3.  0.]]


## QR decomposition

In [14]:
from numpy import array
from numpy.linalg import qr

In [16]:
A = array([[3,0],[4,5]])
print(A)

[[3 0]
 [4 5]]


In [18]:
Q, R =qr(A, 'complete')
print(Q)

[[-0.6 -0.8]
 [-0.8  0.6]]


In [19]:
print(R)

[[-5. -4.]
 [ 0.  3.]]


In [20]:
B=Q.dot(R)
print(B)

[[ 3.  0.]
 [ 4.  5.]]


## reconstruct matrix

In [4]:
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
	[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


## Eigenvector

In [5]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
	[1, 2, 3],
	[4, 5, 6],
	[7, 8, 9]])
# factorize
values, vectors = eig(A)
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


## Eigendecomposition

In [7]:
from numpy import array
from numpy.linalg import eig

In [8]:
B = ([[2,1],[0,3]])
C = ([[5,3], [3,2]])

In [9]:
values, vectors = eig(B)
print(values)

[ 2.  3.]


In [11]:
A = array([[3,0],[4,5]])
print(A)

[[3 0]
 [4 5]]


In [12]:
B1 = array([[-1,-2],[6,6]])
print(B1)

[[-1 -2]
 [ 6  6]]


In [16]:
value, vectors =eig(B1)
print(vectors)

[[-0.5547002   0.4472136 ]
 [ 0.83205029 -0.89442719]]


In [14]:
from numpy import array
from scipy.linalg import lu
F = array ([[2,3,1],[4,1,4],[3,4,6]])
print(F)

[[2 3 1]
 [4 1 4]
 [3 4 6]]


In [43]:
P, L, U = lu(F)
print(P)

[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]


In [44]:
print(L)

[[ 1.          0.          0.        ]
 [ 0.75        1.          0.        ]
 [ 0.5         0.76923077  1.        ]]


In [45]:
print(U)

[[ 4.          1.          4.        ]
 [ 0.          3.25        3.        ]
 [ 0.          0.         -3.30769231]]


In [47]:
F1=L.dot(U)
print(F1)

[[ 4.  1.  4.]
 [ 3.  4.  6.]
 [ 2.  3.  1.]]


In [48]:
F2=P.dot(F1)
print(F2)

[[ 2.  3.  1.]
 [ 4.  1.  4.]
 [ 3.  4.  6.]]


## SVD decomposition

In [17]:
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd

In [18]:
A = array([[3,0],[4,5]])
print(A)

[[3 0]
 [4 5]]


In [19]:
U, s, V =svd(A)
Sigma = diag(s)
print(Sigma)

[[ 6.70820393  0.        ]
 [ 0.          2.23606798]]


In [66]:
B = U.dot(Sigma.dot(V))
print(B)

[[  3.00000000e+00   8.88178420e-16]
 [  4.00000000e+00   5.00000000e+00]]


In [52]:
print(U)

[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]


In [53]:
print(s)

[ 6.70820393  2.23606798]


In [54]:
print(V)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [55]:
print(Sigma)

[[ 0.  0.]
 [ 0.  0.]]


In [59]:
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
print(Sigma)

[[ 6.70820393  0.        ]
 [ 0.          2.23606798]]


In [61]:
B = U. dot(Sigma.dot(V))
print(B)

[[  3.00000000e+00   8.88178420e-16]
 [  4.00000000e+00   5.00000000e+00]]


## ex.singular-value decomposition

In [7]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
	[1, 2],
	[3, 4],
	[5, 6]])
print(A)
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[ 9.52551809  0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## Cholesky decomposition

In [2]:
from numpy import array
from numpy.linalg import cholesky
# define symmetrical matrix
A = array([
	[2, 1, 1],
	[1, 2, 1],
	[1, 1, 2]])
print(A)
# factorize
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[ 1.41421356  0.          0.        ]
 [ 0.70710678  1.22474487  0.        ]
 [ 0.70710678  0.40824829  1.15470054]]
[[ 2.  1.  1.]
 [ 1.  2.  1.]
 [ 1.  1.  2.]]
