## Vector norm

In [1]:
from numpy import array
from numpy.linalg import norm
a = array([[1,1,0]])
print(a)

[[1 1 0]]


In [2]:
l1 = norm(a,1)
print(l1)

1.0


In [5]:
l2 = norm(a)
print(l2)

1.41421356237


In [13]:
from numpy import inf
linf = norm(a, inf)
print(linf)

2.0


## Matrix norm

In [14]:
A = array([[1,4],[2,5],[-1,3]])
print(A)

[[ 1  4]
 [ 2  5]
 [-1  3]]


In [15]:
from numpy import inf
Minf = norm(A, inf)
print(Minf)

7.0


In [22]:
C=a @ A
print(C)

[[3 9]]


In [24]:
c1 =norm (C,1)
print(c1)

9.0


In [26]:
norm(A)

7.4833147735478827

In [28]:
A1 = A@A.T
print(A1)

[[17 22 11]
 [22 29 13]
 [11 13 10]]


In [32]:
from numpy.linalg import inv
from numpy import inf
A2 = inv(A1)
print(A2)
norm(A2, inf)

[[ -2.16566539e+15   1.37815071e+15   5.90636017e+14]
 [  1.37815071e+15  -8.77004995e+14  -3.75859283e+14]
 [  5.90636017e+14  -3.75859283e+14  -1.61082550e+14]]


4134452116930292.0