## Vector Addtion

1. Solve for x
$$u=\begin{pmatrix}
2\\
-1\\
5\\
0\end{pmatrix} , v=\begin{pmatrix}
4\\
-3\\
1\\
-1
\end{pmatrix}, \ \ 
w=\begin{pmatrix}
-6\\2\\0\\3\end{pmatrix}$$

(1) x=2u-(v+3w)

In [56]:
from numpy import array
u = array([2,-1,5,0])
v = array([4,-3,1,-1])
w=array([-6,2,0,3])
#3w
c = 3
a = c*w
#2u
d=2
e = d*u
x=d*u - (v+a)
print(x) #[18 -5  9 -8]

[18 -5  9 -8]


(2) 3(x+w)=2u-v+x
    x=u-(1/2)v-(3/2)w

In [74]:
from numpy import array
u = array([2,-1,5,0])
v = array([4,-3,1,-1])
w=array([-6,2,0,3])
i= 1/2
j=3/2
x = u - i*v - j*w
print(x) # [9.  -2.5  4.5 -4. ]

[ 9.  -2.5  4.5 -4. ]


## Operation (dot, tensor)

(3) x=u dot v

In [75]:
x=u.dot(v)
print(x) #16

16


2. Solve the A tensor B

In [86]:
from numpy import array
from numpy import tensordot
A = array([[2],[3]])
B = array([[1,5],[2,4]])
C=tensordot(A, B, axes=0)
print(C) 
#[[[[ 2 10]
#   [ 4  8]]]


# [[[ 3 15]
#   [ 6 12]]]]

[[[[ 2 10]
   [ 4  8]]]


 [[[ 3 15]
   [ 6 12]]]]


3. Write x as a linear combination of u and w. if possible.

X=[0,3]^t
u=[1.2]^T
w=[1,-1]^T

In [106]:
x=array([[0,3]])
X=x.T
u=array([[1,2]])
U=u.T
w=array([[1,-1]])
W=w.T
a=1
b=-1
Y=a*u+b*w

5. Show that the vectors u,v are orthogonal

In [119]:
u=array([[3,2,-1,4]])
v=array([[1,-1,1,0]])
u.dot(v.T) #array([[0]])

array([[0]])