In [21]:
import numpy as np

In [22]:
# column vector
c = np.array([1,2,3])
print(c.shape)

# obtaining a particular entry
print (c[0])

(3,)
1


In [23]:
# row vector
r = np.array([ [1,2,3] ])
print (r.shape)

(1, 3)


In [24]:
# obtaining a particular entry
print (r[0,1])

2


In [25]:
# creating a matrix with all zeros
a = np.zeros((2,2))
print (a)
# creating a matrix with all ones
b = np.ones((2,2))
print (b)
             
# creating a matrix filled with the same constant
c = np.full((2,2), 7)
print (c)
             
# creating a matrix with random values
d = np.random.random((2,2))
print (d)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]
[[7 7]
 [7 7]]
[[ 0.93589863  0.19331487]
 [ 0.14309097  0.43003853]]


In [26]:
# creating a matrix
A=np.array([[1,2],[3,4],[5,6]])
print (A)


[[1 2]
 [3 4]
 [5 6]]


In [27]:
# creating another matrix
B=np.array([[11,12,13,14],[15,16,17,18]])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [28]:
# transpose a matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [29]:
# matrix-matrix multiplication
np.dot(A,B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [30]:
# matrix-matrix multiplication 
# size should match!
np.dot(B,A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [31]:
# coefficient matrix A and a vector b
A=np.array([[60, 5.5, 1],[65, 5.0, 0],[55, 6.0, 1]])
b=np.array([66, 70, 78])

In [33]:
# identity matrix 
eye3 = np.eye(3)
eye3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [35]:
# computing an inverse
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [36]:
# wrong matrix multiplication
A*A_inv

array([[  5.21739130e+00,   4.78260870e-02,  -8.69565217e-02],
       [ -7.34782609e+01,   4.34782609e-01,   0.00000000e+00],
       [  1.10000000e+02,  -6.00000000e+00,  -1.00000000e+00]])

In [38]:
# correct matrix multiplication
A.dot(A_inv)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [40]:
# solution of a linear system
x=A_inv.dot(b)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [41]:
# a better way to solve the same linear system
from numpy.linalg import solve
x = solve(A,b)
x

array([ -0.43478261,  19.65217391, -16.        ])