## Linear system 

Solve Ax=b using inverse of A

In [25]:
from numpy import array
A=array([[60,5.5,1],[65,5.0,0],[55,6.0,1]])
b=array([[66,70,78]])
print(A)
print(b)

[[ 60.    5.5   1. ]
 [ 65.    5.    0. ]
 [ 55.    6.    1. ]]
[[66 70 78]]


In [3]:
from numpy.linalg import inv
x=inv(A).dot(b.T)
print(x)

[[ -0.43478261]
 [ 19.65217391]
 [-16.        ]]


Solve Ax=b using 'solve'

In [4]:
from numpy.linalg import solve
x = solve(A,b.T)
print(x)

[[ -0.43478261]
 [ 19.65217391]
 [-16.        ]]


Solve the $$\begin{pmatrix}
1&2\\
3&4
\end{pmatrix} \begin{pmatrix}
x\\
y
\end{pmatrix} =\begin{pmatrix}
-1\\
1
\end{pmatrix}$$

$x=\frac{4\cdot -1-2\cdot 1}{1\cdot 4-2\cdot 3}=\frac{-6}{-2}=3$

$y=\frac{1\cdot 1-3\cdot -1}{1\cdot 4-2\cdot 3}=\frac{4}{-2}=-2$


In [5]:
from numpy import array
A=array([[1,2],[3,4]])
b=array([[-1,1]])
print(A)
print(b)

[[1 2]
 [3 4]]
[[-1  1]]


In [6]:
from numpy.linalg import inv
x=inv(A).dot(b.T)
print(x)

[[ 3.]
 [-2.]]


## Type of Matrices

In [8]:
from numpy import array
# list of data
data = [[11, 22],[33, 44],[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [9]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [10]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
from numpy import identity
I = identity(3)
print(I)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
[0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


## Matrix operations

In [13]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [14]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735393e-16


In [ ]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

In [17]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2


In [18]:
# sparse matrix
from numpy import array
from scipy.sparse import csr_matrix
# create dense matrix
A = array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)
# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print(S)
# reconstruct dense matrix
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [19]:
# sparsity calculation
from numpy import array
from numpy import count_nonzero
# create dense matrix
A = array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)
# calculate sparsity
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222


In [20]:
# create tensor
from numpy import array
T = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [21]:
# tensor addition
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# add tensors
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


$$\begin{pmatrix}
1&2\\
\end{pmatrix} \otimes \begin{pmatrix}
3&4
\end{pmatrix} =\begin{pmatrix}
3&4\\
6&8
\end{pmatrix}$$

In [22]:
# tensor product
from numpy import array
from numpy import tensordot
# define first vector
A = array([1,2])
# define second vector
B = array([3,4])
# calculate tensor product
C = tensordot(A, B, axes=0)
print(C)

[[3 4]
 [6 8]]


## Gram-Schmidt Process

In [39]:
from numpy import array
x1=array([3,6,0])
y2=array([1,2,2])
print('x1=',x1)
print('y2=',y2)
y2.dot(x1)

x1= [3 6 0]
y2= [1 2 2]


15

In [43]:
from numpy import array
x1=array([3,6,0])
y2=array([1,2,2])
a1=y2.dot(x1)
aa=x1.dot(x1)
x2=y2-(a1/aa)*x1
print(x2)

15
[ 0.  0.  2.]


In [44]:
x1.dot(x2)

0.0