## Linear system 

Solve Ax=b using inverse of A

In [8]:
from numpy import array
A=array([[60,5.5,1],[65,5.0,0],[55,6.0,1]])
b=array([[66,70,78]])
print(A)
print(b)

[[ 60.    5.5   1. ]
 [ 65.    5.    0. ]
 [ 55.    6.    1. ]]
[[66 70 78]]


In [10]:
from numpy.linalg import inv
x=inv(A).dot(b.T)
print(x)

[[ -0.43478261]
 [ 19.65217391]
 [-16.        ]]


Solve Ax=b using 'solve'

In [12]:
from numpy.linalg import solve
x = solve(A,b.T)
print(x)

[[ -0.43478261]
 [ 19.65217391]
 [-16.        ]]
