## Matrices and linear transformation

1. Find the product. Let $$A=\begin{pmatrix}
3&1\\
2&1
\end{pmatrix}, \ \ B^T =\begin{pmatrix}
1&4\\
2&5\\
-1&3
\end{pmatrix}$$

In [1]:
#create matrix
from numpy import array

A=array([[3,1],[2,1]])
print(A)
A.shape

[[3 1]
 [2 1]]


(2, 2)

In [2]:
from numpy import array
B1=array([[1,4],[2,5],[-1,3]])
print(B1)
B1.shape

[[ 1  4]
 [ 2  5]
 [-1  3]]


(3, 2)

In [3]:
#transpose
B=B1.T
print(B)
B.shape

[[ 1  2 -1]
 [ 4  5  3]]


(2, 3)

1. $A^2$

In [4]:
#Multiply matrices 
C=A.dot(A)
print(C)

[[11  4]
 [ 8  3]]


In [5]:
#Multiply mtrices with @operator
D= A @ A
print(D)

[[11  4]
 [ 8  3]]


$2. \ A^T B$


In [6]:
A1=(A.T).dot(B)
print(A1)

[[11 16  3]
 [ 5  7  2]]


In [7]:
(A.T)@B

array([[11, 16,  3],
       [ 5,  7,  2]])

$3. \ A^T$

In [8]:
F = A.T
print(F)

[[3 2]
 [1 1]]


$4. (A^T B)^{-1}$

In [9]:
from numpy import array
from numpy.linalg import inv
inv(F.dot(B))

LinAlgError: Last 2 dimensions of the array must be square

$5. A^{-1}$

In [10]:
inv(A)

array([[ 1., -1.],
       [-2.,  3.]])

$6. \ (BB^T )^{-1}$

In [11]:
inv(B@(B.T))

array([[ 0.27932961, -0.06145251],
       [-0.06145251,  0.03351955]])

In [12]:
B.T

array([[ 1,  4],
       [ 2,  5],
       [-1,  3]])

In [13]:
B@(B.T)

array([[ 6, 11],
       [11, 50]])

$7.$ Consider a linear tranformation $T: \ R^2 \rightarrow R^3$, $T(x)=Ax$. 


Let $A=\begin{pmatrix}
1 & 0 &3 \\
4 & 5 &-1 \\
0 & 0 &2 \end{pmatrix}$,  For $x=\begin{pmatrix} 1\\2\\5 \end{pmatrix}$. Compute $T(x)$.

In [14]:
AA=array([[1,0,3],[4,5,-1],[0,0,2]])
print(AA)

[[ 1  0  3]
 [ 4  5 -1]
 [ 0  0  2]]


In [15]:
X=array([[1],[2],[5]])
print(X)

[[1]
 [2]
 [5]]


In [16]:
AA@X

array([[16],
       [ 9],
       [10]])